# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='general_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.IntegerField(default=0)),
                ('module_id', models.IntegerField(default=0)),
                ('ip', models.CharField(default='0', max_length=50)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('val', models.FloatField(default=0.0)),
                ('err', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='normal_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField(default=0)),
                ('ip', models.CharField(default='0', max_length=50)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity1', models.FloatField(default=0.0)),
                ('humidity2', models.FloatField(default=0.0)),
                ('err', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='temp_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField(default=0)),
                ('ip', models.CharField(default='0', max_length=50)),
                ('temperature1', models.FloatField(default=0.0)),
                ('temperature2', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('err', models.IntegerField(default=0)),
            ],
        ),
    ]
