# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='general_module',
            new_name='module',
        ),
    ]
