# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171221_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_module',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 18, 8, 54, 633415)),
        ),
    ]
