# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_general_module_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thresh', models.FloatField(default=0.0)),
                ('temp_high', models.FloatField(default=0.0)),
                ('temp_low', models.FloatField(default=0.0)),
                ('night_diff', models.FloatField(default=0.0)),
                ('high_hour', models.IntegerField(default=0)),
                ('low_hour', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='general_module',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 20, 36, 16, 967683)),
        ),
    ]
