# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171221_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='critical_humidity',
            field=models.IntegerField(default=560),
        ),
        migrations.AlterField(
            model_name='general_module',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 15, 30, 46, 49227)),
        ),
    ]
