# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171228_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_module',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general_module',
            name='hours2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general_module',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general_module',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general_module',
            name='seconds2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='general_module',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 12, 58, 10, 143686)),
        ),
    ]
